#!/usr/bin/env node
/**
 * Generate the Tailwind theme from Polaris's real tokens.
 *
 * Mechanical on purpose. Hand-copying hundreds of values guarantees drift the
 * first time Polaris ships a change, and "looks roughly like Polaris" is not
 * what was asked for. Run this again after bumping @shopify/polaris-tokens.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const HERE = dirname(fileURLToPath(import.meta.url));

const cssPath = require.resolve('@shopify/polaris-tokens/css/styles.css');
const css = readFileSync(cssPath, 'utf8');

/** Every --p-* custom property Polaris publishes. */
const tokens = new Map();
for (const [, name, value] of css.matchAll(/--p-([a-z0-9-]+)\s*:\s*([^;}]+)/g)) {
  tokens.set(name, value.trim());
}
if (tokens.size === 0) throw new Error('no tokens parsed — did the package layout change?');

const group = (prefix) =>
  [...tokens.entries()]
    .filter(([name]) => name.startsWith(`${prefix}-`))
    .map(([name, value]) => [name.slice(prefix.length + 1), value]);

/** Tailwind namespace → Polaris token prefix. */
const NAMESPACES = [
  ['--color', 'color'],
  ['--spacing', 'space'],
  ['--radius', 'border-radius'],
  ['--shadow', 'shadow'],
  ['--font-size', 'font-size'],
  ['--font-weight', 'font-weight'],
  ['--leading', 'font-line-height'],
  ['--tracking', 'font-letter-spacing'],
  ['--ease', 'motion-ease'],
  ['--duration', 'motion-duration'],
  ['--z', 'z-index'],
  ['--breakpoint', 'breakpoints'],
];

const lines = [
  '/*',
  ' * GENERATED by scripts/build-theme.mjs — do not edit.',
  ' *',
  ' * Maps @shopify/polaris-tokens into Tailwind 4 theme namespaces, so a',
  ' * utility like bg-surface or p-400 resolves to the real Polaris value',
  ' * rather than an approximation of it.',
  ' */',
  "@import 'tailwindcss';",
  "@import '@shopify/polaris-tokens/css/styles.css';",
  '',
  '@theme {',
];

let count = 0;
for (const [namespace, prefix] of NAMESPACES) {
  const entries = group(prefix);
  if (!entries.length) continue;
  lines.push(`  /* ${prefix} — ${entries.length} tokens */`);
  for (const [name, value] of entries) {
    // Reference the custom property rather than inlining the value, so the
    // published token remains the single source of truth at runtime too.
    lines.push(`  ${namespace}-${name}: var(--p-${prefix}-${name}, ${value});`);
    count++;
  }
  lines.push('');
}
lines.push('}', '');

mkdirSync(join(HERE, '..', 'src', 'styles'), { recursive: true });
writeFileSync(join(HERE, '..', 'src', 'styles', 'theme.generated.css'), lines.join('\n'));

console.log(`parsed ${tokens.size} Polaris tokens`);
console.log(`wrote ${count} Tailwind theme entries across ${NAMESPACES.length} namespaces`);
for (const [ns, prefix] of NAMESPACES) {
  const n = group(prefix).length;
  if (n) console.log(`  ${ns.padEnd(14)} <- --p-${prefix}-*  (${n})`);
}
